// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjFRyrD4G6QYxMh7x-UMDcOU-sNo_7FW0',
    appId: '1:697878172470:web:2cc5caaa520337da66d997',
    messagingSenderId: '697878172470',
    projectId: 'webapp-597b8',
    authDomain: 'webapp-597b8.firebaseapp.com',
    storageBucket: 'webapp-597b8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt9t-64HwLZMA9hs7ku_j6l7CsLcZbTYQ',
    appId: '1:697878172470:android:baccc45c8c04ba1a66d997',
    messagingSenderId: '697878172470',
    projectId: 'webapp-597b8',
    storageBucket: 'webapp-597b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZSfaFgiVJ3iGTlnY3aAIgeiXOS_WMlnA',
    appId: '1:697878172470:ios:c6a41cb7b094269766d997',
    messagingSenderId: '697878172470',
    projectId: 'webapp-597b8',
    storageBucket: 'webapp-597b8.firebasestorage.app',
    iosBundleId: 'com.example.dashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZSfaFgiVJ3iGTlnY3aAIgeiXOS_WMlnA',
    appId: '1:697878172470:ios:c6a41cb7b094269766d997',
    messagingSenderId: '697878172470',
    projectId: 'webapp-597b8',
    storageBucket: 'webapp-597b8.firebasestorage.app',
    iosBundleId: 'com.example.dashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjFRyrD4G6QYxMh7x-UMDcOU-sNo_7FW0',
    appId: '1:697878172470:web:e69b5a62f2a7b84666d997',
    messagingSenderId: '697878172470',
    projectId: 'webapp-597b8',
    authDomain: 'webapp-597b8.firebaseapp.com',
    storageBucket: 'webapp-597b8.firebasestorage.app',
  );
}
